name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: string
                description: "Target version number for the release"
    push:
        tags:
            - "v*.*.*"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v4
            -
                uses: robinraju/release-downloader@v1
                with:
                    repository: hstuart/jtestmemprofiler-cpp
                    latest: false
                    tag: ${{ inputs.version || github.ref_name }}
                    fileName: "*"
                    out-file-path: "artifacts"
            -
                run: ls -lR
            -
                uses: actions/setup-java@v4
                name: Setup Java
                with:
                    distribution: "temurin"
                    java-version: 17
            -
                uses: gradle/actions/setup-gradle@v4
                name: Setup Gradle
            -
                name: Run publish
                env:
                    MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                    GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                run: ./gradlew publishToCentralPortal --info
